### ISSUE TITLE
issue installing them

### ISSUE THREAD

**Issue by kaspardavid** [emcconne/surfagility#4]
Hi

this is what i read on my browser screen when installing surfagility on wordpress:

Parse error: syntax error, unexpected T_FUNCTION in /homepages/43/d119014430/htdocs/starserveur/BEE/wp-content/themes/surfagility-master/functions.php on line 51

thanks for advice

regards

**Comment by Jusung** [comment]
I had same issue. This is caused by your PHP version.
To use this theme you should have PHP 5.3 or later.
In my case manually disabled related code because my hosting server is using PHP 5.2

**Comment by kaspardavid** [comment]
Thank you for the solution. It works fine now!

regards

**Comment by Jusung** [comment]
Cool!

**Comment by kaspardavid** [comment]
)))
