### ISSUE TITLE
I want to remove post-sidebar

### ISSUE THREAD

**Issue by Jusung** [emcconne/surfagility#5]
Hello, I love this theme.
But I like to chafe some part of it can you help me?
I want to get rid of "post-sidebar" in a post because I prefer center-aligned post content.
So I tried deleting all "post-sidebar" part in "single.php" and removed .post-sidebar thing in "surfgility.less" file but no luck.

Can you tell me how can I take out this "post-sidebar" part and I can use center aligned post content?

Here is a link of my blog-post http://kyejusung.dothome.co.kr/?p=25
I want to place this yellow background part to center but I can't.

**Comment by emcconne** [comment]
This theme uses Bootstrap for column sizing so you also have to change the post-content class.  Change the class of post-content from col-lg-8 col-sm-8 to col-lg-12 col-sm-12 and see if that helps.

**Comment by Jusung** [comment]
Thank you very much! I will try like that!
